In [1]:
from sklearn import datasets
import numpy as np
import pandas as pd

In [2]:
def write_answer(ans, file_name):
    with open(file_name, "w") as fout:
        fout.write(str (ans))

In [3]:
digits = datasets.load_digits()
breast_cancer = datasets.load_breast_cancer()

In [4]:
digits_data = pd.DataFrame(digits.data)
digits_target = pd.DataFrame(digits.target)
breast_cancer_data = pd.DataFrame(breast_cancer.data)
breast_cancer_target = pd.DataFrame(breast_cancer.target)

In [5]:
digits_data.head()

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

In [6]:
breast_cancer_data.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB

## Бернулли

In [8]:
estimator = BernoulliNB()
score = cross_val_score(estimator, digits_data, np.array(digits_target).ravel(), scoring='accuracy', cv=3)
print ("accuracy по digits:")
print (score.mean())

print()

estimator = BernoulliNB()
score = cross_val_score(estimator, breast_cancer_data, np.array(breast_cancer_target).ravel(), scoring='accuracy', cv=3)
print ("accuracy по breast_cancer:")
print (score.mean())

accuracy по digits:
0.8235948803561491

accuracy по breast_cancer:
0.6274204028589994

## Мультиномиальное

In [9]:
estimator = MultinomialNB()
score = cross_val_score(estimator, digits_data, np.array(digits_target).ravel(), scoring='accuracy', cv=3)
print ("accuracy по digits:")
print (score.mean())

print()

estimator = MultinomialNB()
score = cross_val_score(estimator, breast_cancer_data, np.array(breast_cancer_target).ravel(), scoring='accuracy', cv=3)
print ("accuracy по breast_cancer:")
print (score.mean())

accuracy по digits:
0.870895937673901

accuracy по breast_cancer:
0.8945790401930752

## Гауссовское

In [10]:
estimator = GaussianNB()
score = cross_val_score(estimator, digits_data, np.array(digits_target).ravel(), scoring='accuracy', cv=3)
print ("accuracy по digits:")
print (score.mean())

print()

estimator = GaussianNB()
score = cross_val_score(estimator, breast_cancer_data, np.array(breast_cancer_target).ravel(), scoring='accuracy', cv=3)
print ("accuracy по breast_cancer:")
print (score.mean())

accuracy по digits:
0.8135781858653311

accuracy по breast_cancer:
0.9367492806089297

### Вопрос 1

Каким получилось максимальное качество классификации на датасете breast_cancer?

In [11]:
write_answer(0.9367492806089297, "bayes_1")

### Вопрос 2

Каким получилось максимальное качество классификации на датасете digits?

In [12]:
write_answer(0.870895937673901, "bayes_2")

### Вопрос 3

Выберите верные утверждения и запишите их номера через пробел (в порядке возрастания номера):

1) На вещественных признаках лучше всего сработал наивный байесовский классификатор с распределением Бернулли

2) На вещественных признаках лучше всего сработал наивный байесовский классификатор с мультиномиальным распределением

3) Мультиномиальное распределение лучше показало себя на выборке с целыми неотрицательными значениями признаков

4) На вещественных признаках лучше всего сработало нормальное распределение

In [13]:
write_answer("3 4", "bayes_3")